name: 'GitHub Action for deleting a GitHub Package'
description: 'This is a GitHub Action for deleting a GitHub Package.'

branding:
  icon: package
  color: blue

inputs:
  owner:
    description: The owner of the package
    required: false
  package-name:
    description: The name of the package
    required: true
  package-version:
    description: The version of the package
    required: true
  package-type:
    description: The type of supported package
    required: true

runs:
  using: node16
  main: dist/index.js
